---
- name: Check file existence
  ansible.builtin.stat:
    path: /run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  become: yes
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists == True
